name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew link --force gettext
          export PATH="$(brew --prefix gettext)/bin:$PATH"  # Dynamically set PATH for gettext
          export LDFLAGS="-L$(brew --prefix gettext)/lib"  # Update linker flags dynamically
          export CPPFLAGS="-I$(brew --prefix gettext)/include"  # Update preprocessor flags
      
          # Verify and create symlink for the required library
          GETTEXT_LIB_PATH="$(brew --prefix gettext)/lib/libintl.8.dylib"
          if [ ! -f "$GETTEXT_LIB_PATH" ]; then
            echo "Creating missing symlink for libintl.8.dylib..."
            sudo mkdir -p /usr/local/opt/gettext/lib
            sudo ln -s "$GETTEXT_LIB_PATH" /usr/local/opt/gettext/lib/libintl.8.dylib
          fi
      
          # Confirm the library is accessible
          if [ ! -f /usr/local/opt/gettext/lib/libintl.8.dylib ]; then
            echo "Error: libintl.8.dylib could not be found or linked."
            exit 1
          fi

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install
        run: |
          pip install -e .
          pip install -r requirements_dev.txt

      - name: Run tests
        run: pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
