name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew link gettext --force

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Upgrade setuptools and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install
        run: |
          pip install --upgrade 'setuptools<68.0.0'  
          pip install -e .
          pip install -r requirements_dev.txt
          pip install --upgrade build

      - name: Run tests
        run: pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
