name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew link --force gettext
          export PATH="/usr/local/opt/gettext/bin:$PATH"  # Ensure gettext binaries are in the PATH
          export LDFLAGS="-L/usr/local/opt/gettext/lib"  # Update linker flags
          export CPPFLAGS="-I/usr/local/opt/gettext/include"  # Update C preprocessor flags
          # Explicitly verify and create symlinks if necessary
          if [ ! -f /usr/local/opt/gettext/lib/libintl.8.dylib ]; then
            echo "gettext library not found, creating symlink..."
            ln -s /usr/local/Cellar/gettext/*/lib/libintl.8.dylib /usr/local/opt/gettext/lib/libintl.8.dylib
          fi

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install
        run: |
          pip install -e .
          pip install -r requirements_dev.txt

      - name: Run tests
        run: pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
