name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew link --force gettext
          export PATH="$(brew --prefix gettext)/bin:$PATH"  # Dynamically set PATH for gettext
          export LDFLAGS="-L$(brew --prefix gettext)/lib"  # Update linker flags dynamically
          export CPPFLAGS="-I$(brew --prefix gettext)/include"  # Update preprocessor flags
          # Explicitly verify and create symlinks if necessary
          if [ ! -f "$(brew --prefix gettext)/lib/libintl.8.dylib" ]; then
            echo "gettext library not found, creating symlink..."
            ln -s $(brew --prefix gettext)/lib/libintl.8.dylib /usr/local/opt/gettext/lib/libintl.8.dylib
          fi

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install
        run: |
          pip install -e .
          pip install -r requirements_dev.txt

      - name: Run tests
        run: pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
